// <auto-generated />
using System;
using ContaPlusAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContaPlusAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230516204351_AddedTables")]
    partial class AddedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyUser", b =>
                {
                    b.Property<Guid>("CompaniesCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompaniesCompanyId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("CompanyUser");
                });

            modelBuilder.Entity("ContaPlusAPI.Models.AccountingModule.CompanyChartOfAccounts", b =>
                {
                    b.Property<int>("CompanyChartOfAccountsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyChartOfAccountsId"));

                    b.Property<int>("AccountCode")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyChartOfAccountsId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyChartOfAccounts");
                });

            modelBuilder.Entity("ContaPlusAPI.Models.AccountingModule.GeneralChartOfAccounts", b =>
                {
                    b.Property<int>("AccountCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountCode"));

                    b.Property<string>("AccountDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Product_Service")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountCode");

                    b.ToTable("GeneralChartOfAccounts");
                });

            modelBuilder.Entity("ContaPlusAPI.Models.AccountingModule.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreditAccountCode")
                        .HasColumnType("int");

                    b.Property<int>("DebitAccountCode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreditAccountCode");

                    b.HasIndex("DebitAccountCode");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ContaPlusAPI.Models.CompanyModule.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiscalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Signature")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SocialCapital")
                        .HasColumnType("int");

                    b.Property<string>("TradeRegister")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TvaPayer")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ContaPlusAPI.Models.CompanyModule.UserCompanyRole", b =>
                {
                    b.Property<Guid>("UserCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserCompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCompanyRoles");
                });

            modelBuilder.Entity("ContaPlusAPI.Models.UserModule.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "accountant"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "manager"
                        });
                });

            modelBuilder.Entity("ContaPlusAPI.Models.UserModule.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleUserCompanyRole", b =>
                {
                    b.Property<int>("RolesRoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("RolesUserCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesRoleId", "RolesUserCompanyId");

                    b.HasIndex("RolesUserCompanyId");

                    b.ToTable("RoleUserCompanyRole");
                });

            modelBuilder.Entity("CompanyUser", b =>
                {
                    b.HasOne("ContaPlusAPI.Models.CompanyModule.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContaPlusAPI.Models.UserModule.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContaPlusAPI.Models.AccountingModule.CompanyChartOfAccounts", b =>
                {
                    b.HasOne("ContaPlusAPI.Models.CompanyModule.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ContaPlusAPI.Models.AccountingModule.Transaction", b =>
                {
                    b.HasOne("ContaPlusAPI.Models.CompanyModule.Company", "Company")
                        .WithMany("Transactions")
                        .HasForeignKey("CompanyId");

                    b.HasOne("ContaPlusAPI.Models.AccountingModule.GeneralChartOfAccounts", "CreditAccount")
                        .WithMany()
                        .HasForeignKey("CreditAccountCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ContaPlusAPI.Models.AccountingModule.GeneralChartOfAccounts", "DebitAccount")
                        .WithMany()
                        .HasForeignKey("DebitAccountCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreditAccount");

                    b.Navigation("DebitAccount");
                });

            modelBuilder.Entity("ContaPlusAPI.Models.CompanyModule.UserCompanyRole", b =>
                {
                    b.HasOne("ContaPlusAPI.Models.CompanyModule.Company", "Company")
                        .WithMany("UserCompanyRoles")
                        .HasForeignKey("CompanyId");

                    b.HasOne("ContaPlusAPI.Models.UserModule.User", "User")
                        .WithMany("UserCompanyRoles")
                        .HasForeignKey("UserId");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleUserCompanyRole", b =>
                {
                    b.HasOne("ContaPlusAPI.Models.UserModule.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContaPlusAPI.Models.CompanyModule.UserCompanyRole", null)
                        .WithMany()
                        .HasForeignKey("RolesUserCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContaPlusAPI.Models.CompanyModule.Company", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("UserCompanyRoles");
                });

            modelBuilder.Entity("ContaPlusAPI.Models.UserModule.User", b =>
                {
                    b.Navigation("UserCompanyRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
